### ISSUE TITLE
If we check table data, no one will lose the game.

### ISSUE THREAD

**Issue by firesWu** [CryptoLions/roshambo-EOS-contract#1]
if play1 create game, and input move_hash by move1, and then play2 input move_hash by move1 and input move and move_nonce by move2. In this moment, db has play2's data.  it can tell play1 if he will win, so play1 directly closes the game if he lost. By the way, someone will use move2 first, so other can get table to know   `ph_move` or `pc_move`, and then know this game result, so host can close the game or challenger will never input move by move2.

**Comment by orange1337** [comment]
> if play1 create game, and input move_hash by move1, and then play2 input move_hash by move1 and input move and move_nonce by move2. In this moment, db has play2's data. it can tell play1 if he will win, so play1 directly closes the game if he lost. By the way, someone will use move2 first, so other can get table to know `ph_move` or `pc_move`, and then know this game result, so host can close the game or challenger will never input move by move2.

Thanks for reply. We'll plug this hole in next release.

**Comment by ansigroup** [comment]
https://github.com/CryptoLions/roshambo-EOS-contract/commit/5ae2ea095a81961d335749ef9d8ceb0d4b3cbaaa

**Comment by firesWu** [comment]
when challenger will never input move by move2， challenger hasn't nothing to lose cause ram payer is host. and now , host can not cancel game so he can't get his ram back.

**Comment by ansigroup** [comment]
correct, thanks, we will fix this

**Comment by ansigroup** [comment]
Hi, fixed in roshambo 2.0
